### ISSUE TITLE
How to use dropWhile?

### ISSUE THREAD

**Issue by juhp** [bawolk/hsp#2]
I was trying to do
`hsp 'dropWhile (not . ("abi-depends" `T.isPrefixOf`)) pp'`
but got a type error: `Couldn't match type ‘Line T.Text’ with ‘T.Text’`.

How should one do something like this in hsp?
I couldn't really find a comparable example in the README documentation.

**Comment by bawolk** [comment]
Sorry it took so long for me to get back to you.  After installing a cabal-install setup I managed to ruin my stack setup and after fiddling around, neither works.  I have been busy with other things and have just now (fingers crossed) fixed my tooling.  As to your question, `pp` is not a [Text], but instead it is a [Line Text].  I now realize that I made a poor record name choice, so one would need to pattern match to pull out the Text field.  Something like
`hsp 'dropWhile (\(Line _ t _) -> (not . (T.isPrefixOf "abi-depends")) t ) pp :: [SLine]'`
will work.  Obviously we can do better! The type declaration is currently needed because the hint typeOf function calls the result {Line T.Text], not the equivalent [SLine], which is what hsp looks for.  I will fix this to allow something like hsp 'dropWhile (not . (T.isPrefixOf "abi-depends") . getText ) pp .

**Comment by juhp** [comment]
Thank you for the explanation :-)

**Comment by bawolk** [comment]
Updated master. https://github.com/bawolk/hsp/commit/8ffb02a6a9e510676e8f5baa2ea7adccad351ee2

**Comment by juhp** [comment]
Thanks a lot!

This is so cool - I can now do for example:

```
$ cat mypkg.spec | hsp 'takeWhile ((/= "%changelog") . getText) pp | p'
```

to hide the changelog from rpm spec files.

I can also re-implement juhp/lsfrom as just `ls | hsp 'dropWhile ((< '$1') . getText) pp | p'`.
